using Microsoft.EntityFrameworkCore;
using AutoGeneratedApi.Models;

namespace AutoGeneratedApi.Data;

public class ApiContext(DbContextOptions<ApiContext> options) : DbContext(options)
{
    public DbSet<Country> Countries { get; set; } = default!;

    public DbSet<Capital> Capitals { get; set; } = default!;

    public DbSet<Album> Albums { get; set; } = default!;
    public DbSet<Song> Songs { get; set; } = default!;
    public DbSet<Movie> Movies { get; set; } = default!;
    public DbSet<Genre> Genres { get; set; } = default!;

}
