using AutoGeneratedApi.Models;
using System.ComponentModel.DataAnnotations;

namespace AutoGeneratedApi.ViewModels
{
    public class GenreViewModle
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public required string Name { get; set; }

        public ICollection<Movie>? Movies { get; set; }

        public bool IsSelected { get; set; }
    }
}
