using AutoGeneratedApi.Models;
using AutoGeneratedApi.ViewModels;

namespace AutoGeneratedApi.ViewModels
{
    public class MovieAndGenre
    {
        public Movie? Movie { get; set; } 
        public List<Genre> Genres { get; set; } = new List<Genre>();
        public List<GenreViewModle> GenreViewModle { get; set; } = new List<GenreViewModle>();
    }
}
