using AutoGeneratedApi.Models;

namespace AutoGeneratedApi.ViewModels
{
    public class SongAndAlbumsViewModels
    {
        public Song Song { get; set; } = new Song() { Name = string.Empty, Length=0};
        public List<Album> Albums { get; set; } = [];

    }
}
