using System.ComponentModel.DataAnnotations;

namespace AutoGeneratedApi.Models
{
    public class Album
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public required string Name { get; set; }

        public ICollection<Song> Songs { get; set; } = [];
    }
}
