using System.ComponentModel.DataAnnotations;

namespace AutoGeneratedApi.Models
{
    public class Capital
    {
        [Key]
        public int Id { get; set; }

        [Required , MinLength(1)]
        public required string Name { get; set; }

        [Required]
        public required Country Country { get; set; }

        public int CountryId { get; set; }
    }
}
