using System.ComponentModel.DataAnnotations;

namespace AutoGeneratedApi.Models
{
    public class Country
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public required string Name { get; set; }

        [Required]
        [StringLength(50)]
        public required string Continent { get; set; }

        public Capital? Capital { get; set; }
    }
}
