using System.ComponentModel.DataAnnotations;

namespace AutoGeneratedApi.Models
{
    public class Genre
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public required string Name { get; set; }

        public ICollection<Movie>? Movies { get; set; }

        
    }
}
