using System.ComponentModel.DataAnnotations;

namespace AutoGeneratedApi.Models
{
    public class Movie
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public required string Title { get; set; }

        [Required, MinLength(10)]
        public required string Description { get; set; }

        [Required]  
        public required double length { get; set; }

        public ICollection<Genre> MGenres { get; set; }
    }
}
