using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AutoGeneratedApi.Migrations
{
    /// <inheritdoc />
    public partial class UpdatedGenreModle : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "isSelected",
                table: "Genres",
                type: "bit",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "isSelected",
                table: "Genres");
        }
    }
}
