using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AutoGeneratedApi.Data;
using AutoGeneratedApi.Models;
using AutoGeneratedApi.ViewModels;

namespace AutoGeneratedApi.Controllers
{
    public class SongsController : Controller
    {
        private readonly ApiContext _context;

        public SongsController(ApiContext context)
        {
            _context = context;
        }

        // GET: Songs
        public async Task<IActionResult> Index()
        {
            var songs = await _context.Songs.Include(s => s.Album).ToListAsync();
            return View(songs);
        }

        // GET: Songs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var song = await _context.Songs.Include(s => s.Album)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (song == null)
            {
                return NotFound();
            }

            return View(song);
        }

        // GET: Songs/Create
        public async Task<IActionResult> Create()
        {
            var albums  = await _context.Albums.ToListAsync();

            SongAndAlbumsViewModels SAviewmodle = new SongAndAlbumsViewModels();
            SAviewmodle.Albums = albums;


            return View(SAviewmodle);
        }

        // POST: Songs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SongAndAlbumsViewModels viewModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(viewModel.Song);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //     var albums = await _context.Albums.ToListAsync();
            //     ViewBag.Albums = albums;
            var albums = await _context.Albums.ToListAsync();
            SongAndAlbumsViewModels SAviewmodle = new SongAndAlbumsViewModels();
            SAviewmodle.Albums = albums;
            return View(SAviewmodle);
        }

        // GET: Songs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var albums = await _context.Albums.ToListAsync();
            SongAndAlbumsViewModels SAviewmodle = new SongAndAlbumsViewModels();
            SAviewmodle.Albums = albums;
            var song = await _context.Songs.FindAsync(id);
            if (song == null)
            {
                return NotFound();
            }
            SAviewmodle.Song = song;
            return View(SAviewmodle);
        }

        // POST: Songs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, SongAndAlbumsViewModels viewModel)
        {
            if (id != viewModel.Song.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(viewModel.Song);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SongExists(viewModel.Song.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        // GET: Songs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var song = await _context.Songs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (song == null)
            {
                return NotFound();
            }

            return View(song);
        }

        // POST: Songs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var song = await _context.Songs.FindAsync(id);
            if (song != null)
            {
                _context.Songs.Remove(song);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SongExists(int id)
        {
            return _context.Songs.Any(e => e.Id == id);
        }
    }
}
